### ISSUE TITLE
Node.js 20.16.0

### ISSUE THREAD

**Issue by Klaus-Lucas** [Apollon77/ioBroker.mbus#377]
Bitte updaten

![klu_006](https://github.com/user-attachments/assets/62a46bb3-f14d-4442-a983-7881364fb94c)

**Comment by alx785** [comment]
ich habe auch Probleme seid einem Update auf Node 20.16.0. Scheint die gleiche Meldung zu sein.

`2024-08-04 01:28:11.993 - info: host.ioBroker-240330 Restart adapter system.adapter.mbus.0 because enabled`
`2024-08-04 01:28:18.881 - info: host.ioBroker-240330 "system.adapter.mbus.0" disabled`
`2024-08-04 01:28:42.650 - error: host.ioBroker-240330 Caught by controller[0]: `
```
/opt/iobroker/node_modules/bindings/bindings.js:121
throw e;
^
Error: Module did not self-register: '/opt/iobroker/node_modules/node-mbus/build/Release/mbus.node'.
at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
at Module.load (node:internal/modules/cjs/loader:1208:32)
at Module._load (node:internal/modules/cjs/loader:1024:12)
at Module.require (node:internal/modules/cjs/loader:1233:19)
at require (node:internal/modules/helpers:179:18)
at bindings (/opt/iobroker/node_modules/bindings/bindings.js:112:48)
at Object. (/opt/iobroker/node_modules/node-mbus/index.js:7:40)
at Module._compile (node:internal/modules/cjs/loader:1358:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
at Module.load (node:internal/modules/cjs/loader:1208:32) {
code: 'ERR_DLOPEN_FAILED'
}
Node.js v20.16.0
instance system.adapter.mbus.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
```

Würde mich über ein update freuen. Vielen Dank!

**Comment by Apollon77** [comment]
Seems the module was not rebuild after your nodejs upgrade, so please
* cd /opt/iobroker/node_modules/node-mbus
* rm -rf build
* npm rebuild

Try again

**Comment by alx785** [comment]
fine. that works for me, thanks!

**Comment by Klaus-Lucas** [comment]
Hallo Ingo,

bei mir jetzt auch ok.
Vielen Dank für den Tipp.
